CREATE TABLE IF NOT EXISTS tbl (id INT PRIMARY KEY AUTO_INCREMENT, item VARCHAR(50));
INSERT INTO tbl (item) VALUES ('35');
INSERT INTO tbl (item) VALUES ('45');
INSERT INTO tbl (item) VALUES ('61');
INSERT INTO tbl (item) VALUES ('59');
INSERT INTO tbl (item) VALUES ('73');