CREATE TABLE IF NOT EXISTS tbl (id INT PRIMARY KEY AUTO_INCREMENT, item VARCHAR(50));
INSERT INTO tbl (item) VALUES ('66');
INSERT INTO tbl (item) VALUES ('166');
INSERT INTO tbl (item) VALUES ('202');
INSERT INTO tbl (item) VALUES ('14');